Feature/conf d support
wirenboard/wb-homa-gpio pull request #13
Opened 2020-07-07 09:26 UTC by PeteK12

1. Добавил поддержку conf.d
2. Перевёл на systemd
3. Сделал Alias сервису на wb-homa-gpio

2020-07-07 09:29 UTC, evgeny-boger commented on wb-mqtt-gpio.schema.json
> +                            "minimum": 1,
а почему 1?

2020-07-07 09:31 UTC, PeteK12 commented on wb-mqtt-gpio.schema.json
> +                            "minimum": 1,
В старом коде была проверка на больше 0

2020-07-07 09:37 UTC, PeteK12 commented on wb-mqtt-gpio.schema.json
> +                            "minimum": 1,
@evgeny-boger https://github.com/wirenboard/wb-homa-gpio/blob/ae179acec076ba89495e9563860afb2a2018f4dd/config.cpp#L297

2020-07-07 09:40 UTC, evgeny-boger commented on wb-mqtt-gpio.schema.json
> +                            "minimum": 1,
не очень понимаю. номер gpio отрицательным быть не может, а нулём может быть. В коде тоже `>= 0`. Так что в схеме правильно было, получается.

2020-07-07 09:44 UTC, PeteK12 commented
Да. Точно

2020-07-10 04:21 UTC, PeteK12 commented
Тоже поменял порядок разбора параметров командной строки, чтоб не делало core dump.

2020-07-15 20:26 UTC, evgeny-boger commented
```
root@wirenboard-ADOMRKK5:~# wb-mqtt-gpio 
INFO: [mqtt] connection estabilished with code "0" <success>
INFO: [mqtt] subscription succeeded (message id 1)
INFO: [mqtt] subscription succeeded (message id 2)
INFO: [utils] Sysfs GPIO number 109 => GPIO line 3: 13
ERROR: [gpio] FATAL: duplicate GPIO name in config: 'A1_IN' at chip '/dev/gpiochip3' @ config.cpp:43
terminate called without an active exception
Аварийный останов
```

нам нужно в каком-то виде сделать возможность переопределения пользователем для настроек. Раньше оно было. Надо подумать, как это лучше сделать.

2020-07-16 05:13 UTC, PeteK12 commented
@evgeny-boger Можно по имени смотреть, если в wb-mqtt-gpio.conf повтор, то отдавать предпочтение настроке из него, ну и предупреждение кинуть в лог. В adc так и сделано, в gpio же ещё до меня было исключение на этом месте, потому и не стал менять.
Там ещё есть проверка, что встречаются 2 одинаковых gpio под разными именами. Это тоже приводит к выходу из программы.

2020-07-16 10:09 UTC, evgeny-boger commented
>@evgeny-boger Можно по имени смотреть, если в wb-mqtt-gpio.conf повтор, то отдавать предпочтение настроке из него, ну и предупреждение кинуть в лог.

да, давай вот так

>Там ещё есть проверка, что встречаются 2 одинаковых gpio под разными именами. Это тоже приводит к выходу из программы.

тоже видел, это наверное можно оставить.

2020-07-16 12:25 UTC, PeteK12 commented
@evgeny-boger done

2020-07-20 12:08 UTC, PeteK12 commented
Добавил зависимость от wb-configs, чтоб симлинки на настройки не перезатирались

2020-09-06 17:21 UTC, evgeny-boger requested changes

2020-09-06 17:21 UTC, evgeny-boger commented on config.cpp
> +            IterateDirByPattern(mainConfigFile + ".d", ".conf", [&](const string& f) {
тоже не будет читать /var/lib/ ?

2020-09-06 17:21 UTC, evgeny-boger commented on config.h
> +                             const std::string& shemaFile);
schema

2020-09-06 17:21 UTC, evgeny-boger commented on file_utils.h
> +#pragma once
копипаста же с wb-mqtt-adc? В нескольких других местах тоже. Стоит подумать, куда это деть.

2020-09-07 04:37 UTC, PeteK12 commented on file_utils.h
> +#pragma once
Да, скопировано. Можно в libwbmqtt1 перенести, либо переехать на компилятор с C++17, там есть std::filesystem и большая часть этого файла не нужна.

2020-09-07 08:06 UTC, merged